import { AppSidebar } from "@/components/app-sidebar"; // Adjust the path as needed
import { SidebarProvider } from "@/components/ui/sidebar"; // Import SidebarProvider
import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div style={{ display: "flex" }}>
            {/* Add the sidebar component */}
            <AppSidebar />
            {/* Main content area */}
            <div style={{ flex: 1, paddingLeft: "250px" }}>
              {/* Children components, like the page content */}
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
